src/Entity/Tweet.php
<?php

namespace AlexisLefebvre\Bundle\AsyncTweetsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * Tweet.
 */
class Tweet
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $created_at;

    /**
     * @var string
     */
    private $text;

    /**
     * @var int
     */
    private $retweet_count = 0;

    /**
     * @var int
     */
    private $favorite_count = 0;

    /**
     * @var User
     */
    private $user;

    /**
     * In timeline: false for retweeted Tweets.
     *
     * @var bool
     */
    private $in_timeline = false;

    /**
     * @var Tweet
     */
    private $retweeted_status = null;

    /**
     * @var Collection<int, Tweet>
     */
    private $retweeting_statuses;

    /**
     * @var Collection<int, Media>
     */
    private $medias;

    public function __construct()
    {
        $this->medias = new ArrayCollection();
        $this->retweeting_statuses = new ArrayCollection();
    }

    /**
     * Set id.
     *
     * @return Tweet
     */
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Set created_at.
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->created_at = $createdAt;

        return $this;
    }

    /**
     * Get created_at.
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    /**
     * Set text.
     */
    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    /**
     * Get text.
     */
    public function getText(): string
    {
        return $this->text;
    }

    public function getTextLinkified(): ?string
    {
        /* @see http://stackoverflow.com/questions/507436/how-do-i-linkify-urls-in-a-string-with-php/507459#507459 */
        return preg_replace(
            '~[[:alpha:]]+://[^<>[:space:]]+[[:alnum:]/]~',
            '<a href="\\0">\\0</a>',
            $this->getText()
        );
    }

    /**
     * Set retweet_count.
     */
    public function setRetweetCount(int $retweetCount): self
    {
        $this->retweet_count = $retweetCount;

        return $this;
    }

    /**
     * Get retweet_count.
     */
    public function getRetweetCount(): int
    {
        return $this->retweet_count;
    }

    /**
     * Set favorite_count.
     */
    public function setFavoriteCount(int $favoriteCount): self
    {
        $this->favorite_count = $favoriteCount;

        return $this;
    }

    /**
     * Get favorite_count.
     */
    public function getFavoriteCount(): int
    {
        return $this->favorite_count;
    }

    /**
     * Set user.
     */
    public function setUser(User $user): self
    {
        $this->user = $user;
        $this->user->addTweet($this);

        return $this;
    }

    /**
     * Get User.
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * Set in timeline.
     */
    public function setInTimeline(bool $inTimeline): self
    {
        $this->in_timeline = $inTimeline;

        return $this;
    }

    /**
     * Get in timeline.
     */
    public function isInTimeline(): bool
    {
        return $this->in_timeline;
    }

    /**
     * Set retweeted
     * "This attribute contains a representation of the original Tweet
     *  that was retweeted.".
     */
    public function setRetweetedStatus(self $retweetedStatus): self
    {
        $this->retweeted_status = $retweetedStatus;

        return $this;
    }

    /**
     * Get retweeted status.
     */
    public function getRetweetedStatus(): ?self
    {
        return $this->retweeted_status;
    }

    /**
     * Get medias.
     *
     * @return Collection<int, Media>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Media $media): self
    {
        $this->medias->add($media);
        $media->addTweet($this);

        return $this;
    }

    public function removeMedia(Media $media): self
    {
        $this->medias->removeElement($media);
        $media->removeTweet($this);

        return $this;
    }

    /**
     * Get retweeting status.
     *
     * @return Collection<int, Tweet>
     */
    public function getRetweetingStatuses(): Collection
    {
        return $this->retweeting_statuses;
    }

    /**
     * Call setter functions.
     */
    public function setValues(\stdClass $tweetTmp): self
    {
        $this
            ->setCreatedAt(new \DateTime($tweetTmp->created_at))
            ->setText($tweetTmp->text)
            ->setRetweetCount($tweetTmp->retweet_count)
            ->setFavoriteCount($tweetTmp->favorite_count);

        return $this;
    }

    /**
     * Check that tweet can be deleted.
     */
    public function mustBeKept(int $tweetId): bool
    {
        if (count($this->getRetweetingStatuses()) == 0) {
            // This tweet has not been retweeted
            return false;
        }

        // Check that this tweet has not been retweeted after $tweetId
        foreach ($this->getRetweetingStatuses() as $retweeting_status) {
            // This tweet is retweeted in the timeline, keep it
            if ($retweeting_status->getId() >= $tweetId) {
                return true;
            }
        }

        return false;
    }
}

src/Entity/User.php
<?php

namespace AlexisLefebvre\Bundle\AsyncTweetsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * User.
 */
class User
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $screen_name;

    /**
     * @var string|null
     */
    private $profile_image_url;

    /**
     * @var string|null
     */
    private $profile_image_url_https;

    /**
     * @var Collection<int, Tweet>
     */
    private $tweets;

    public function __construct(?int $id = null)
    {
        if (!is_null($id)) {
            $this->setId($id);
        }

        $this->tweets = new ArrayCollection();
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Set name.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Set screen_name.
     */
    public function setScreenName(string $screenName): self
    {
        $this->screen_name = $screenName;

        return $this;
    }

    /**
     * Get screen_name.
     */
    public function getScreenName(): string
    {
        return $this->screen_name;
    }

    /**
     * Set profile_image_url.
     */
    public function setProfileImageUrl(?string $profileImageUrl): self
    {
        $this->profile_image_url = $profileImageUrl;

        return $this;
    }

    /**
     * Get profile_image_url.
     */
    public function getProfileImageUrl(): ?string
    {
        return $this->profile_image_url;
    }

    /**
     * Set profile_image_url_https.
     */
    public function setProfileImageUrlHttps(?string $profileImageUrlHttps): self
    {
        $this->profile_image_url_https = $profileImageUrlHttps;

        return $this;
    }

    /**
     * Get profile_image_url_https.
     */
    public function getProfileImageUrlHttps(): ?string
    {
        return $this->profile_image_url_https;
    }

    /**
     * Get profile image, with HTTPS if available.
     */
    public function getProfileImageUrlHttpOrHttps(): ?string
    {
        if (!is_null($this->getProfileImageUrlHttps())) {
            return $this->getProfileImageUrlHttps();
        }
        // else

        return $this->getProfileImageUrl();
    }

    /**
     * Get tweets.
     *
     * @return Collection<int, Tweet>
     */
    public function getTweets(): Collection
    {
        return $this->tweets;
    }

    /**
     * Add a tweet.
     */
    public function addTweet(Tweet $tweet): self
    {
        $this->tweets->add($tweet);

        return $this;
    }

    /**
     * Call setter functions.
     */
    public function setValues(\stdClass $userTmp): self
    {
        $this
            ->setName($userTmp->name)
            ->setScreenName($userTmp->screen_name)
            ->setProfileImageUrlHttps($userTmp->profile_image_url_https);

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace AlexisLefebvre\Bundle\AsyncTweetsBundle\Controller;

use AlexisLefebvre\Bundle\AsyncTweetsBundle\Entity\Tweet;
use AlexisLefebvre\Bundle\AsyncTweetsBundle\Entity\TweetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController as BaseController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;

// Compatibility layer for Symfony 3.4
if (!class_exists('Symfony\Bundle\FrameworkBundle\Controller\Controller')) {
    class_alias('Symfony\Bundle\FrameworkBundle\Controller\Controller', 'Symfony\Bundle\FrameworkBundle\Controller\AbstractController');
}

class DefaultController extends BaseController
{
    /** @var EntityManagerInterface */
    private $entityManager;

    /** @var TweetRepository */
    private $tweetRepository;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function indexAction(Request $request, ?int $firstTweetId): Response
    {
        /** @var TweetRepository $tweetRepository */
        $tweetRepository = $this->entityManager
            ->getRepository(Tweet::class);

        $this->tweetRepository = $tweetRepository;

        $tweets = $this->tweetRepository
            ->getWithUsersAndMedias($firstTweetId);

        $variables = $this->getVariables($request, $tweets, $firstTweetId);

        $response = $this->render(
            '@AsyncTweets/Default/index.html.twig',
            [
                'tweets' => $tweets,
                'vars'   => $variables,
            ]
        );

        if (!is_null($variables['cookie'])) {
            /** @var Cookie $cookie */
            $cookie = $variables['cookie'];
            $response->headers->setCookie($cookie);
        }

        return $response;
    }

    /**
     * @param array<Tweet> $tweets
     *
     * @return array<Cookie|int|string|null>
     */
    private function getVariables(Request $request, array $tweets, ?int $firstTweetId): array
    {
        $vars = [
            'first'    => $firstTweetId,
            'previous' => null,
            'next'     => null,
            'number'   => 0,
            'cookieId' => $this->getLastTweetIdFromCookie($request),
            // No cookie by default
            'cookie' => null,
        ];

        if (count($tweets) > 0) {
            $vars = $this->getTweetsVars($tweets, $vars);
        }

        return $vars;
    }

    /**
     * If a Tweet is displayed, fetch data from repository.
     *
     * @param array<Tweet>                  $tweets
     * @param array<Cookie|int|string|null> $vars
     *
     * @return array<Cookie|int|string|null>
     */
    private function getTweetsVars(array $tweets, array $vars): array
    {
        /** @var int $firstTweetId */
        $firstTweetId = $tweets[0]->getId();

        $vars['previous'] = $this->tweetRepository
            ->getPreviousTweetId($firstTweetId);
        $vars['next'] = $this->tweetRepository
            ->getNextTweetId($firstTweetId);

        // Only update the cookie if the last Tweet Id is bigger than
        //  the one in the cookie
        if ($firstTweetId > $vars['cookieId']) {
            $vars['cookie'] = $this->createCookie($firstTweetId);
            $vars['cookieId'] = $firstTweetId;
        }

        /** @var int */
        $cookieId = $vars['cookieId'];
        $vars['number'] = $this->tweetRepository
            ->countPendingTweets($cookieId);

        $vars['first'] = $firstTweetId;

        return $vars;
    }

    private function getLastTweetIdFromCookie(Request $request): ?int
    {
        if ($request->cookies->has('lastTweetId')) {
            return (int) $request->cookies->get('lastTweetId');
        }

        return null;
    }

    private function createCookie(int $firstTweetId): Cookie
    {
        $nextYear = new \DateTime('now');
        $nextYear->add(new \DateInterval('P1Y'));

        // Set last Tweet Id
        $cookie = new Cookie(
            'lastTweetId',
            (string) $firstTweetId,
            $nextYear->format('U')
        );

        return $cookie;
    }

    public function resetCookieAction(): RedirectResponse
    {
        /* @see http://www.craftitonline.com/2011/07/symfony2-how-to-set-a-cookie/ */
        $response = new RedirectResponse(
            $this->generateUrl('asynctweets_homepage')
        );

        // Reset last Tweet Id
        $cookie = new Cookie('lastTweetId', null);
        $response->headers->setCookie($cookie);

        return $response;
    }

    public function deleteLessThanAction(Request $request): RedirectResponse
    {
        $lastTweetId = $this->getLastTweetIdFromCookie($request);

        if (!is_null($lastTweetId)) {
            /** @var TweetRepository $tweetRepository */
            $tweetRepository = $this->entityManager
                ->getRepository(Tweet::class);

            $count = $tweetRepository
                ->deleteAndHideTweetsLessThanId($lastTweetId);

            /** @var Session<int> $session */
            $session = $this->get('session');

            $session->getFlashBag()->add(
                'message',
                sprintf('%s tweets deleted.', $count)
            );
        }

        return $this->redirect($this->generateUrl('asynctweets_homepage'));
    }
}

src/Resources/views/Default/index.html.twig
{% extends '@AsyncTweets/layout.html.twig' %}

{% block title %}Home timeline - {% if (vars.first is not null)
    %}since {{ vars.first }}{%
endif%}{% endblock %}

{% block content %}
    {# display navigation #}
    <div class="navigation row">
        {% set pagination %}
        <div class="col-sm-5 col-xs-12">
            <ul class="pagination">
                <li class="{{ ((vars.previous is null) ? 'disabled') }}">
                    {% if (vars.previous is not null) %}
                        <a href="{{ path('asynctweets_tweets_sinceTweetId', {
                            'firstTweetId': vars.previous
                        }) }}">«&nbsp;Previous</a>
                    {% else %}
                        <span>«&nbsp;Previous</span>
                    {% endif %}
                </li>
                
                <li class="{{ ((vars.next is null) ? 'disabled') }}">
                    {% if (vars.next is not null) %}
                        <a href="{{ path('asynctweets_tweets_sinceTweetId', {
                            'firstTweetId': vars.next
                        }) }}">Next&nbsp;»</a>
                    {% else %}
                        <span>Next&nbsp;»</span>
                    {% endif %}
                </li>
            </ul>
        </div>
        {% endset %}
        
        {{ pagination }}
        
        <div class="col-sm-7 col-xs-12 count alert alert-info">
            {% if (vars.cookieId is not null) %}
                <p>
                    Last tweet id:
                    <a href="{{ path('asynctweets_tweets_sinceTweetId', {
                            'firstTweetId': vars.cookieId
                        }) }}">{{ vars.cookieId }}</a>
                    <a href="{{ path('asynctweets_reset_cookie') }}"
                        class="btn btn-default btn-xs">
                        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                        Reset cookie
                    </a>
                    <a href="{{ path('asynctweets_tweets_delete') }}"
                        class="btn btn-default btn-xs" id="tweets-delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        Delete old tweets
                    </a>
                </p>
            {% endif %}
            
            <p>{{ vars.number }} pending tweets</p>
        </div>
    </div>
    
    <div class="tweets">
        {% for tweet in tweets %}
            {% if (tweet.retweetedStatus) %}
                {% include '@AsyncTweets/Default/retweet_inc.html.twig' %}
            {% else %}
                {% include '@AsyncTweets/Default/tweet_inc.html.twig' %}
            {% endif %}
        {% else %}
            <p>No tweet to display.</p>
        {% endfor %}
    </div>
    
    {# display navigation #}
    <div class="navigation row">
        {{ pagination }}
        <div class="col-sm-7 col-xs-12 alert alert-info" role="alert">
            Press <kbd>←</kbd> and <kbd>→</kbd> to go to previous or next page.
        </div>
    </div>
{% endblock %}

src/Resources/views/Default/retweet_inc.html.twig
{# see http://getbootstrap.com/components/#media #}
<div class="media">
    <div class="media-left media-middle">
        <img src="{{ tweet.user.profileImageUrlHttpOrHttps }}" width="48" height="48"
            class="media-object" alt="{{ tweet.user.name }}"
            title="{{ tweet.user.name }}" />
    </div>
    <blockquote class="media-body">
        {% include '@AsyncTweets/Default/tweet_inc.html.twig'
            with {
                'tweet': tweet.retweetedStatus,
                'mark_as_read_link': false
        } %}
        
        <small>
            <a href="{{
                'https://twitter.com/%user_name%'|replace({
                    '%user_name%': tweet.user.screenName
                })
            }}">{{ tweet.user.name }}</a>,
            <a href="{{
                'https://twitter.com/%user_name%/status/%tweet_id%'|replace({
                    '%user_name%': tweet.user.screenName,
                    '%tweet_id%': tweet.id
                })
            }}">{{ tweet.createdAt|date('c') }}</a>
            
            <span class="badge">
                <span class="glyphicon glyphicon-retweet"></span>
                {{ tweet.retweetCount }}
            </span>
            
            <span class="badge">
                <span class="glyphicon glyphicon-heart"></span>
                {{ tweet.favoriteCount }}
            </span>
            
            <a href="{{ path('asynctweets_tweets_sinceTweetId',
                {'firstTweetId': tweet.id}) }}" class="pull-right">
                <span class="glyphicon glyphicon-check"></span>
                Mark as read
            </a>
        </small>
    </blockquote>
</div>

src/Resources/views/Default/tweet_inc.html.twig
{# see http://getbootstrap.com/components/#media #}
<div class="media">
    <div class="media-left media-middle">
        <img src="{{ tweet.user.profileImageUrlHttpOrHttps }}" width="48" height="48"
            class="media-object" alt="{{ tweet.user.name }}"
            title="{{ tweet.user.name }}" />
    </div>
    <blockquote class="media-body">
        <p>{{ tweet.textLinkified|raw }}</p>
        {% for media in tweet.medias %}
            {% if loop.first %}<p>{% endif %}
                <a href="{{ media.expandedUrl }}" title="{{ media.displayUrl }}">
                    <img src="{{ media.mediaUrlHttps }}"
                    alt="{{ media.url }}" /></a>
            {% if loop.last %}</p>{% endif %}
        {% endfor %}
        <small>
            <a href="{{
                'https://twitter.com/%user_name%'|replace({
                    '%user_name%': tweet.user.screenName
                })
            }}">{{ tweet.user.name }}</a>,
            <a href="{{
                'https://twitter.com/%user_name%/status/%tweet_id%'|replace({
                    '%user_name%': tweet.user.screenName,
                    '%tweet_id%': tweet.id
                })
            }}">{{ tweet.createdAt|date('c') }}</a>
            
            <span class="badge">
                <span class="glyphicon glyphicon-retweet"></span>
                {{ tweet.retweetCount }}
            </span>
            
            <span class="badge">
                <span class="glyphicon glyphicon-heart"></span>
                {{ tweet.favoriteCount }}
            </span>
            
            {% if (mark_as_read_link is not defined) %}
                <a href="{{ path('asynctweets_tweets_sinceTweetId',
                    {'firstTweetId': tweet.id}) }}" class="pull-right">
                    <span class="glyphicon glyphicon-check"></span>
                    Mark as read
                </a>
            {% endif %}
        </small>
    </blockquote>
</div>